// <auto-generated />
using System;
using CloudApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CloudApp.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CloudAppDbContext))]
    partial class CloudAppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CloudAppServer.Domain.Entities.CloudFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CloudFolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DownloadCount")
                        .HasColumnType("integer");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Size")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CloudFolderId");

                    b.HasIndex("UserId");

                    b.ToTable("CloudFiles");
                });

            modelBuilder.Entity("CloudAppServer.Domain.Entities.CloudFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCloudFolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentCloudFolderId");

                    b.HasIndex("UserId");

                    b.ToTable("CloudFolders");
                });

            modelBuilder.Entity("CloudAppServer.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DiskSpaceLeft")
                        .HasColumnType("numeric");

                    b.Property<decimal>("FreeDiskSpace")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CloudAppServer.Domain.Entities.CloudFile", b =>
                {
                    b.HasOne("CloudAppServer.Domain.Entities.CloudFolder", "CloudFolder")
                        .WithMany()
                        .HasForeignKey("CloudFolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CloudAppServer.Domain.Entities.User", "User")
                        .WithMany("CloudFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CloudAppServer.Domain.ValueObjects.PublicUrl", "PublicUrl", b1 =>
                        {
                            b1.Property<Guid>("CloudFileId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PublicUrl");

                            b1.HasKey("CloudFileId");

                            b1.ToTable("CloudFiles");

                            b1.WithOwner()
                                .HasForeignKey("CloudFileId");
                        });

                    b.Navigation("CloudFolder");

                    b.Navigation("PublicUrl");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CloudAppServer.Domain.Entities.CloudFolder", b =>
                {
                    b.HasOne("CloudAppServer.Domain.Entities.CloudFolder", "ParentCloudFolder")
                        .WithMany("SubFolders")
                        .HasForeignKey("ParentCloudFolderId");

                    b.HasOne("CloudAppServer.Domain.Entities.User", "User")
                        .WithMany("CloudFolders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CloudAppServer.Domain.ValueObjects.PublicUrl", "PublicUrl", b1 =>
                        {
                            b1.Property<Guid>("CloudFolderId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("PublicUrl");

                            b1.HasKey("CloudFolderId");

                            b1.ToTable("CloudFolders");

                            b1.WithOwner()
                                .HasForeignKey("CloudFolderId");
                        });

                    b.Navigation("ParentCloudFolder");

                    b.Navigation("PublicUrl");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CloudAppServer.Domain.Entities.User", b =>
                {
                    b.OwnsOne("CloudAppServer.Domain.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Email");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Email")
                        .IsRequired();
                });

            modelBuilder.Entity("CloudAppServer.Domain.Entities.CloudFolder", b =>
                {
                    b.Navigation("SubFolders");
                });

            modelBuilder.Entity("CloudAppServer.Domain.Entities.User", b =>
                {
                    b.Navigation("CloudFiles");

                    b.Navigation("CloudFolders");
                });
#pragma warning restore 612, 618
        }
    }
}
